reload "orion.plugins"
-- reload "orion.neuron"
reload "orion.options"
reload "orion.keys"
-- reload "orion.chatgpt"
reload "orion.jaq"
-- reload "orion.icons"
reload "orion.todo"
reload "orion.fidget"
reload "orion.dap-virtual-text"
reload "orion.statusline"
reload "orion.hop-set"
reload "orion.neural-set"

-- reload "orion.cmdline"
