reload "orion.plugins"
-- reload "orion.neuron"
reload "orion.options"
reload "orion.chatgpt"
reload "orion.jaq"
reload "orion.keys"
-- reload "orion.icons"
reload "orion.todo"
reload "orion.fidget"
reload "orion.dap-virtual-text"
-- reload "orion.cmdline"
